var mongo = require('mongodb');

var sources = [
	{
		src: 'A',
		attrRecipes: [
			{
				name: "color",
				range: ["red", "green", "blue", "yellow", "orange", "pink", "black"]
			},
			{
				name: "animal",
				range: ["croc", "koala", "kangaroo", "cockatoo"]
			},
			{
				name: "weight",
				low: 0,
				high: 100,
				units: "kg"
			}
		]
	}, 
	{
		src: 'B',
		attrRecipes: [
			{
				name: "level",
				low: 0,
				high: 1000
			}
		]
	}
]
var num = 5;
var mongoUrl = "mongodb://127.0.0.1:27017/observabledb";

mongo.connect(mongoUrl , function(err, db) {
	if(err) throw err;
	
	console.log("Successfully connected to mongo at " + mongoUrl);
	
	for(var srcIdx = 0; srcIdx < sources.length ; srcIdx++) {
		console.log("Generating and publishing documents for source " + sources[srcIdx].src);
		db.collection(sources[srcIdx].src).insert(generateDocs(sources[srcIdx], num) , function(err, objects) {
			if(err) throw err;
		});
	}
	//db.close();
});

function generateDocs(src, numDocs) {
	var docs = [];
	for(var i=0; i<numDocs; i++) {
		var doc = {
			id: src.src + i,
			src: src.src,
			t: new Date(),
			desc: "autogenerated observable",
			attrs: generateAttrs(src.attrRecipes),
			geos: [
				{
					id: "location",
					loc: {
						type: "Point",
						coordinates : getCoordinates(39.7392, 104.9847, 25) 
					}
				}
			]
		};
		docs.push(doc);
	}
	//console.log(JSON.stringify(docs, null, 2));
	return docs;
}

function generateAttrs(attrRecipes) {
	var attrs = [];
	for (var recipeIndex=0; recipeIndex<attrRecipes.length; recipeIndex++) {
		var recipe = attrRecipes[recipeIndex];
		var val = "";
		if ('range' in recipe) {
			val = recipe.range[randomFromInterval(0, recipe.range.length)];
		} else if ('low' in recipe || 'high' in recipe) {
			val = randomFromInterval(recipe.low, recipe.high) 
		}
		var attr = {
			k: recipe.name,
			v: val
		}
		if ('units' in recipe) attr.u = recipe.units;
		attrs.push(attr);
	}
	return attrs;
}

//stackoverflow.com/questions/4959975/generate-random-value-between-two-numbers-in-javascript
function randomFromInterval(from, to) {
	var random = Math.floor(Math.random() * (to-from)) + from;
	//console.log("from: " + from + ", to: " + to + ", random: " + random);
	return random;
}

function getCoordinates(cLat, cLon, maxDis_meters) {
	var ONE_METER = 0.00001; //rough estimation of meter in decimal degrees
	var maxDis = maxDis_meters * ONE_METER;
	var coor = []; //lon, lat geojson
	coor[0] = randomFromInterval(cLon-maxDis, cLon+maxDis);
	coor[1] = randomFromInterval(cLat-maxDis, cLon+maxDis);
	return coor;
}
